name: Notify sonder

on:
  push:
    branches:
      - main

jobs:
  notify-sonder-update:
    runs-on: ubuntu-latest
    steps:
    - name: Notify sonder update submodule
      run: |
        curl -X POST https://api.github.com/repos/vitahlin/sonder/dispatches \
          -H "Authorization: token ${{ secrets.SONDER_AND_RYZE_TOKEN }}" \
          -d '{"event_type":"update_submodule_ryze"}'
